---
name: 'Code Quality'

on:
    push:
        branches:
            - main

jobs:
    linting:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout'
              uses: actions/checkout@v2

            - name: 'Setup Node'
              uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: ./

            - name: 'Install Packages'
              working-directory: ./
              run: npm ci

            - name: 'ESLint'
              working-directory: ./
              run: npm run lint
